apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: httpd
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: httpd
    spec:
      containers:
      - name: httpd
        image: httpd
        ports:
        - containerPort : 80
        dnsPolicy: ClusterFirst
---
apiVersion: v1
kind: Service
metadata:
  name: httpd-svc
spec:
 selector:
  run: httpd
 ports:
 -  port: 8080
    targetPort: 80
    protocol: TCP
